// This file is auto-generated by next-intl, do not edit directly.
// See: https://next-intl.dev/docs/workflows/typescript#messages-arguments

declare const messages: {
    "Error": {
        "description": "<p>We've unfortunately encountered an error.</p><p>You can try to <retry>reload the page</retry> you were visiting.</p>",
        "title": "Something went wrong!"
    },
    "LocaleLayout": {
        "title": "Online personal finance dashboard"
    },
    "LocaleSwitcher": {
        "label": "Change language",
        "locale": "{locale, select, de {🇩🇪 Deutsch} en {🇺🇸 English} other {Unknown}}"
    },
    "Manifest": {
        "name": "next-intl example"
    },
    "Navigation": {
        "home": "Home",
        "pathnames": "Pathnames"
    },
    "NotFoundPage": {
        "description": "Please double-check the browser address bar or use the navigation to go to a known page.",
        "title": "Page not found"
    },
    "PageLayout": {
        "links": {
            "docs": {
                "description": "Learn more about next-intl in the official docs.",
                "href": "https://next-intl.dev",
                "title": "Docs"
            },
            "source": {
                "description": "Browse the source code of this example on GitHub.",
                "href": "https://github.com/amannn/next-intl/tree/main/examples/example-app-router",
                "title": "Source code"
            }
        }
    },
    "PathnamesPage": {
        "description": "<p>The pathnames are internationalized too.</p><p>If you're using the default language English, you'll see <code>/en/pathnames</code> in the browser address bar on this page.</p><p>If you change the locale to German, the URL is localized accordingly (<code>/de/pfadnamen</code>).</p>",
        "title": "Pathnames"
    },
    "DashboardHomePage": {
        "title": "Financial Overview",
        "subtitle": "A quick snapshot of your personal financial state, including expenses, budgets, investments, and financial goals.",
        "cards": {
            "totalIncome": "Total Monthly Income",
            "totalExpense": "Total Expenses",
            "savingsRate": "Savings Rate",
            "investmentAssets": "Investment Assets",
            "spendingDistribution": "Spending Distribution",
            "budgetProgress": "Budget Progress by Category",
            "savingsGoals": "Savings Goals Progress",
            "debtOverview": "Debt and Repayment Overview"
        },
        "debtInfo": {
            "remainingDebt": "Remaining Debt",
            "repaymentPlan": "Repayment Plan"
        },
        "currency": "VND",
        "progress": {
            "current": "Current",
            "target": "Target",
            "complete": "Complete"
        }
    },
    "ExpenseCategoriesPage": {
        "title": "Expense Categories",
        "addCategoryTitle": "Add New Category",
        "addCategorySuccess": "Category added successfully!",
        "addCategoryError": "Error adding category",
        "deleteCategorySuccess": "Category deleted successfully!",
        "deleteCategoryError": "Error deleting category",
        "deleteConfirm": "Are you sure you want to delete?",
        "categoryName": "Category Name",
        "categoryDescription": "Description",
        "actions": "Actions",
        "addButton": "Add",
        "placeholderName": "Category Name",
        "placeholderDescription": "Description (optional)",
        "existingCategoriesTitle": "Current Categories List"
    },
    "BudgetPage": {
        "title": "Budget",
        "subtitle": "Track and manage your spending budget to stay within your financial limits.",
        "addBudgetTitle": "Create New Budget",
        "addBudgetSuccess": "Budget added!",
        "addBudgetError": "Error adding budget.",
        "deleteBudgetSuccess": "Budget deleted successfully!",
        "deleteBudgetError": "Error deleting budget.",
        "budgetCategory": "Category",
        "budgetAmount": "Budget",
        "budgetSpent": "Spent",
        "budgetFrequency": "Frequency",
        "overBudgetWarning": "Over budget!",
        "budgetWeekly": "Weekly",
        "budgetMonthly": "Monthly",
        "budgetYearly": "Yearly",
        "budgetAction": "Actions",
        "placeholderCategory": "e.g.: Shopping, Rent...",
        "placeholderAmount": "Enter budget amount",
        "placeholderSpent": "Enter spent amount",
        "placeholderFrequency": "Select frequency",
        "addButton": "Add Budget"
    },
    "GoalsPage": {
        "title": "Financial Goals",
        "subtitle": "Create and monitor your savings progress for short and long term goals.",
        "addGoalTitle": "Add New Goal",
        "addGoalSuccess": "Goal added!",
        "addGoalError": "Failed to add goal",
        "goalName": "Goal Name",
        "goalTargetAmount": "Target Amount",
        "goalSavedAmount": "Saved Amount",
        "goalDeadline": "Deadline",
        "goalProgress": "Savings Progress",
        "timeLeft": "Time Left",
        "addButton": "Add Goal",
        "placeholderName": "e.g.: Buy a motorbike, travel...",
        "placeholderTargetAmount": "Enter target amount",
        "placeholderSavedAmount": "Enter saved amount",
        "placeholderDeadline": "Select deadline"
    },
    "InvestmentsPage": {
        "title": "Investment Tracking",
        "subtitle": "Manage and analyze the performance of your investments over time.",
        "addInvestmentTitle": "Add New Investment",
        "addInvestmentSuccess": "Investment added!",
        "addInvestmentError": "Error adding investment.",
        "investmentName": "Investment Name",
        "investmentType": "Asset Type",
        "investmentAmount": "Investment Value",
        "investmentReturnRate": "Return Rate (%)",
        "totalPortfolio": "Portfolio Overview",
        "totalValue": "Total Value",
        "assetAllocation": "Asset Allocation",
        "investmentDetails": "Portfolio Details",
        "investmentStock": "Stocks",
        "investmentBond": "Bonds",
        "investmentRealEstate": "Real Estate",
        "investmentCrypto": "Cryptocurrency",
        "investmentOther": "Other",
        "addButton": "Add",
        "placeholderName": "Enter investment name",
        "placeholderType": "Select asset type",
        "placeholderAmount": "Enter investment value",
        "placeholderReturnRate": "Enter return rate (%)"
    },
    "DebtManagementPage": {
        "title": "Debt Management",
        "tabs": {
            "overview": "Overview",
            "schedule": "Payment Schedule",
            "plan": "Repayment Plan",
            "add": "Add Debt"
        },
        "addDebtTitle": "Add New Debt",
        "addDebtSuccess": "Debt added!",
        "addDebtError": "Failed to add debt!",
        "debtType": "Debt Type",
        "debtName": "Debt Name",
        "debtTotal": "Total Debt",
        "debtPaid": "Paid",
        "debtRemaining": "Remaining",
        "debtDueDate": "Due Date",
        "debtMonthlyPayment": "Monthly Payment",
        "debtStartDate": "Start Date",
        "debtProgress": "Repayment Progress",
        "debtProjectedPayoff": "Estimated Payoff",
        "paymentSchedule": "Payment Schedule",
        "repaymentPlan": "Repayment Plan",
        "addButton": "Add Debt",
        "placeholderType": "e.g.: Credit Card, Bank Loan...",
        "placeholderName": "Enter debt name",
        "placeholderTotal": "Enter total debt",
        "placeholderPaid": "Enter paid amount",
        "placeholderMonthlyPayment": "Enter monthly payment",
        "placeholderStartDate": "Select start date",
        "placeholderDueDate": "Select due date"
    },
    "ReportsPage": {
        "title": "Reports & Analytics",
        "subtitle": "Summarize your financial data to understand your spending, income, and savings.",
        "loadingMessage": "Loading data...",
        "errorMessage": "Unable to load data. Please try again later.",
        "totalIncome": "Total Income This Month",
        "totalExpense": "Total Expenses This Month",
        "savingRate": "Savings Rate",
        "incomeChartTitle": "Monthly Income Chart",
        "spendingDistributionTitle": "Spending Distribution",
        "tooltipIncome": "Income",
        "tooltipExpense": "Expenses",
        "chartLegend": "Categories",
        "currency": "VND"
    },
    "NotificationsAlertsPage": {
        "title": "Notifications & Alerts",
        "notificationsTitle": "Notifications List",
        "noNotificationsMessage": "No notifications",
        "clearReadButton": "Clear Read",
        "settingsTitle": "Notification Settings",
        "toggleSuccess": "{action} notifications for {type}",
        "notificationTypes": {
            "budget_exceeded": "Budget Exceeded",
            "bill_due": "Bill Due",
            "upcoming_payment": "Upcoming Payment",
            "investment_change": "Investment Change",
            "savings_opportunity": "Savings Opportunity"
        },
        "icons": {
            "budget_exceeded": "🚨",
            "bill_due": "📅",
            "upcoming_payment": "💰",
            "investment_change": "📈",
            "savings_opportunity": "🎯"
        }
    },
    "EducationPage": {
        "title": "Daily Smart Finance",
        "subtitle": "Enhance your personal finance knowledge with tips, tools, and video guides. Take steps to master spending, saving, and investing.",
        "tipsTitle": "Finance Tips",
        "videosTitle": "Finance Videos",
        "toolsTitle": "Support Tools",
        "loadingMessage": "Loading data...",
        "errorMessage": "Unable to load data. Please try again later.",
        "useToolButton": "Use Now"
    },
    "LoginPage": {
        "title": "Login",
        "emailLabel": "Email",
        "emailPlaceholder": "example@email.com",
        "passwordLabel": "Password",
        "passwordPlaceholder": "••••••••",
        "loginButton": "Login",
        "forgotPasswordLink": "Forgot password?",
        "registerAccount": "Don't have an account? ",
        "registerLink": "Register",
        "errorInvalidEmail": "Invalid email",
        "errorRequiredEmail": "Please enter email",
        "errorRequiredPassword": "Please enter password",
        "errorLoginFailed": "Incorrect email or password"
    },
    "RegisterPage": {
        "title": "Register Account",
        "fullnameLabel": "Full Name",
        "fullnamePlaceholder": "John Doe",
        "emailLabel": "Email",
        "emailPlaceholder": "example@email.com",
        "passwordLabel": "Password",
        "passwordPlaceholder": "••••••••",
        "confirmPasswordLabel": "Confirm Password",
        "confirmPasswordPlaceholder": "••••••••",
        "registerButton": "Create Account",
        "loginPrompt": "Already have an account?",
        "loginLink": "Login",
        "errorInvalidEmail": "Invalid email",
        "errorRequiredFullname": "Please enter full name",
        "errorRequiredEmail": "Please enter email",
        "errorRequiredPassword": "Please enter password",
        "errorMinPasswordLength": "Password must be at least 6 characters",
        "errorRequiredConfirmPassword": "Please confirm password",
        "errorPasswordMismatch": "Passwords do not match"
    },
    "ForgotPasswordPage": {
        "title": "Forgot Password",
        "subtitle": "Enter your email address to receive a password reset link.",
        "emailLabel": "Email",
        "emailPlaceholder": "Enter your email address",
        "sendResetLinkButton": "Send Reset Link",
        "resetLinkSuccess": "A password reset link has been sent to your email!",
        "resetLinkError": "Unable to send password reset email!",
        "invalidEmailError": "Please enter a valid email!",
        "counterTitle": "Counter",
        "counterCurrentValue": "Current Value",
        "incrementButton": "Increase",
        "decrementButton": "Decrease",
        "incrementByAmountButton": "Increase by {amount}"
    },
    "ProfilePage": {
        "title": "User Profile",
        "avatarTitle": "Avatar",
        "uploadAvatarButton": "Upload Avatar",
        "avatarUpdateSuccess": "Avatar updated successfully!",
        "profileInfoTitle": "Personal Information",
        "nameLabel": "Full Name",
        "emailLabel": "Email",
        "passwordLabel": "New Password",
        "passwordPlaceholder": "Leave blank if unchanged",
        "saveButton": "Save Changes",
        "profileUpdateSuccess": "Profile updated successfully!",
        "errorInvalidEmail": "Invalid email",
        "errorRequiredName": "Please enter full name",
        "errorRequiredEmail": "Please enter email"
    },
    "CommonLayout": {
        "appName": "FinanceApp",
        "menu": {
            "home": "Home",
            "expenses": "Expenses",
            "budgets": "Budgets",
            "goals": "Goals",
            "investments": "Investments",
            "debts": "Debts",
            "reports": "Reports",
            "notifications": "Notifications",
            "education": "Education"
        },
        "userMenu": {
            "profile": "Profile",
            "logout": "Log Out"
        },
        "toggleSidebar": {
            "expand": "Expand Sidebar",
            "collapse": "Collapse Sidebar"
        }
    },
    "ForgotPassword": {
        "title": "Forgot Password",
        "emailPlaceholder": "Enter your email address",
        "validation": {
            "requiredEmail": "Please input your email!",
            "invalidEmail": "Please enter a valid email!"
        },
        "resetLinkSuccess": "Password reset link sent to your email!",
        "resetLinkFail": "Failed to send password reset email!",
        "sendButton": "Send Reset Link"
    }
};
export default messages;